### ISSUE TITLE
ng-touched not triggered?

### ISSUE THREAD

**Issue by BenevidesLecontes** [NicholasAzar/ng-selectize#24]
Hi! Thanks for your work, i'm trying to use this amazing component, but i can't make ng-touched to trigger, even in the example page, i saw that. Am I missing something?

**Comment by NicholasAzar** [comment]
Hi @BenevidesLecontes, thanks for letting me know about this.. it will be fixed soon.

**Comment by BenevidesLecontes** [comment]
@NicholasAzar and how can i enable other plugins? Like no_results, infinite_scroll and so on?

**Comment by NicholasAzar** [comment]
Fixed here: https://github.com/NicholasAzar/ng-selectize/commit/8b9663734ee943f59cf3edd82b953764d13a16db and form example updated here: https://github.com/NicholasAzar/ng-selectize-demo/commit/e07c563efee9fd3d1ace73a7f0b589d5b13270cb

**Comment by NicholasAzar** [comment]
@BenevidesLecontes The selectize.js script being used actually isn't tied to this plugin, so you're free to use plugins per original selectize documentation https://github.com/selectize/selectize.js/blob/master/docs/plugins.md. Just be sure to set your updated version in the scripts tag of .angular-cli.json (if you're using angular-cli), and pass in the configured plugins through the plugins array in the ng-selectize [config] input param.

**Comment by BenevidesLecontes** [comment]
@NicholasAzar thanks for your clarification, i have my own version of selectizejs, I've used for angularjs projects, now i'm upgrading the NG1 app to Ng2, that's why i'm searching for some plugins and i like this one (ng-selectize). I hope you fix this soon as possible.
