### ISSUE TITLE
(ngModelChange) Not triggred when multiple selection

### ISSUE THREAD

**Issue by JosephSKh** [NicholasAzar/ng-selectize#27]
I'm facing the issue that `(ngModelChange)` is not being triggered when I'm selecting multiple values, it's only triggered the first time with the first selection.

**Comment by JosephSKh** [comment]
It also happens in the online demo, the `console.log` is fired only once
http://nicholasazar.com/ng-selectize/

in the **Dynamically add options to Multi select** example

**Comment by NicholasAzar** [comment]
Thanks for letting me know about this @JosephSKh! I'm considering this high priority and will take a look as soon as I can.

**Comment by JosephSKh** [comment]
@NicholasAzar thx for your fast reply, waiting for the resolve on fire :D

**Comment by NicholasAzar** [comment]
Hey @JosephSKh, this should be all good now, published 1.0.7 with the fix and the docs site is updated. Let me know if you run into any more issues.

**Comment by JosephSKh** [comment]
@NicholasAzar Thank you for your reply and for the fix, I've checked the online demo and **yes it's working**, will be able to check it on my project as well on Sunday.
Thx man :)

**Comment by JosephSKh** [comment]
@NicholasAzar working like a charm, thank u :)
