### ISSUE TITLE
ng-selectize with systemjs

### ISSUE THREAD

**Issue by BenevidesLecontes** [NicholasAzar/ng-selectize#28]
Hi @NicholasAzar i'm trying this component with Systemjs, but it throws this error
<img width="614" alt="screen shot 2017-03-01 at 13 39 19" src="https://cloud.githubusercontent.com/assets/1839361/23470267/b5c46866-fe84-11e6-9159-a692b5e49651.png">

I'm using the umd files. Do you have any idea what's happening?

**Comment by BenevidesLecontes** [comment]
After 2 days searching i found a way to use with systemjs. Thanks anyway.

**Comment by ismaelSilveira** [comment]
Hi @BenevidesLecontes, i'm having same error.
Can you tell me how did you make it work?

Thanks!

**Comment by BenevidesLecontes** [comment]
@ismaelSilveira  you need to do this:

`System.config.map`
```
'ng-selectize': "ng-selectize/bundles/ng-selectize.umd.js",
"node_modules/ng-selectize": {
      "@angular/core": "@angular/core",
      "lodash.clonedeep": "lodash.clonedeep",
      "lodash.differencewith": "lodash.differencewith",
      "lodash.find": "lodash.find",
      "lodash.isequal": "lodash.isequal",
      "reflect-metadata": "reflect-metadata",
      "zone.js": "zone.js"
    },
```

`System.packages`
```
    'ng-selectize': {defaultExtension: 'js', format: 'cjs'},
    "lodash.clonedeep": {defaultExtension: 'js', main: 'index.js'},
    "lodash.differencewith": {defaultExtension: 'js', main: 'index.js'},
    "lodash.find": {defaultExtension: 'js', main: 'index.js'},
    "lodash.isequal": {defaultExtension: 'js', main: 'index.js'},
```

**Comment by ismaelSilveira** [comment]
Works perfect!!
Thanks!

**Comment by NicholasAzar** [comment]
As of version 1.1.0, only lodash.clonedeep is required.
