### ISSUE TITLE
Enable false doesn't work

### ISSUE THREAD

**Issue by BenevidesLecontes** [NicholasAzar/ng-selectize#29]
Hi! Looks like `[enabled]="false"` as default value doesn't work. Even in your example.

**Comment by NicholasAzar** [comment]
Thank you @BenevidesLecontes for letting me know.. looking into it.

**Comment by NicholasAzar** [comment]
Hey @BenevidesLecontes, this is now fixed by https://github.com/NicholasAzar/ng-selectize/commit/c5da2120db5eac5057c0b50c08375538297d4641 and is included in 1.0.8.

**Comment by BenevidesLecontes** [comment]
@NicholasAzar thanks for your amazing work.

**Comment by nanya** [comment]
Hi @NicholasAzar , does this change apply to ng2-selectize as well? Thanks.
