### ISSUE TITLE
(change) event not triggered in ng2-selectize

### ISSUE THREAD

**Issue by nanya** [NicholasAzar/ng-selectize#30]
Hi,
(change)=onValueChange($event) does not seem work with ng2-selectize. The onValueChange function is never called even after a change occurs.

Thanks.

**Comment by NicholasAzar** [comment]
Hey @nanya, could you please try using (ngModelChange) instead and see if that works for you? Please reference the sample here: https://github.com/NicholasAzar/ng-selectize-demo/blob/master/src/app/home/multi-select-example/multiSelectExample.component.html#L5

**Comment by nanya** [comment]
Hi Nicholas, yes the (ngModelChange) works, however, there are cases when a change occurs in the select component (e.g. when a new item is added to the options list dynamically) and the $event (that is the value of the model) of the (ngModelChange) is "" which raises an error in my code. It would be nice to have an (change) event that does not make the ngModel equals to "". Thanks.

**Comment by NicholasAzar** [comment]
Hey @nanya, from my testing I wasn't able to replicate the scenario where adding a new option to the dropdown triggers the ngModelChange with an empty value. If there is a change in the selected value though, if the currently selected value is removed as an option for example, reflecting that the value has changed is correct. I'm struggling to understand why an entirely new event would be preferable to just adding an empty value check in the callback.

I'm going to close this issue for now, but if i'm not understanding the issue properly let's please continue the conversation and maybe it would help if you provided a example of when this event is necessary.

**Comment by nanya** [comment]
Hi @NicholasAzar, I believe adding a change event would be helpful and also to keep things consistent with Angular2 (I am not sure but I think Angular 2 has a change event and an ngModelChange event).

Thanks for your help.
