### ISSUE TITLE
Error when not finish a search

### ISSUE THREAD

**Issue by ismaelSilveira** [NicholasAzar/ng-selectize#31]
Hi.

First of all, sorry for my bad english.

I found that when the partial result of a search is highlighted and the control's focus is lost, the list closes correctly, but when the control is focused again, the list appears and the elements that match with previous search are still highlighted

Search is highlighted properly
![image](https://cloud.githubusercontent.com/assets/2218217/23920523/d10097f8-08d9-11e7-9407-c2a3f178e314.png)

Control is focused again
![image](https://cloud.githubusercontent.com/assets/2218217/23920661/50594b58-08da-11e7-97c0-da06bc4eb30b.png)

Thanks!

**Comment by BenevidesLecontes** [comment]
@ismaelSilveira i'm portuguese, i'll try with english too. This bug is reported on selectize.js repo and it has a PR  also. I created my own version of selectizejs with some corrections and and some plugins, because of these errors.

**Comment by NicholasAzar** [comment]
@BenevidesLecontes would you be able to add a pr for that fix to https://github.com/NicholasAzar/ng-selectize/blob/master/src/selectize/selectize.standalone.js ? I've been aware of this issue for a while now as well and just disabled the highlight feature while i wait for time to take a look.. if you already have though I would love to have it integrated

**Comment by BenevidesLecontes** [comment]
@NicholasAzar i'll do do a PR for this.

**Comment by NicholasAzar** [comment]
Thanks again to @BenevidesLecontes for PR #34 that resolves this issue.
