### ISSUE TITLE
Show display optionGroups?

### ISSUE THREAD

**Issue by danielfnz** [NicholasAzar/ng-selectize#36]
Hello, @NicholasAzar .

I want to use a <optgroup>, how to code it?
See screen on selectize.js.
http://oi66.tinypic.com/29wo67m.jpg

Is the option optionGroups?

Thanks

**Comment by BenevidesLecontes** [comment]
@danielfnz here a small example. Put something like that in your ng-selectize config.
```
optgroups: [
						{value: 'mammal', label: 'Mammal', label_scientific: 'Mammalia'},
						{value: 'bird', label: 'Bird', label_scientific: 'Aves'},
						{value: 'reptile', label: 'Reptile', label_scientific: 'Reptilia'}
					],
					optgroupField: 'class',
					labelField: 'name',
					searchField: ['name'],
					render: {
						optgroup_header: function(data, escape) {
							return '<div class="optgroup-header">' + escape(data.label) + ' <span class="scientific">' + escape(data.label_scientific) + '</span></div>';
						}
					}
```

**Comment by nanya** [comment]
This works exactly as you have it. However, in the 'optgroups' array, if the property names (label or value) are replaced with user-defined fields, it doesn't seem to work even after defining the unique field names using 'optgroupLabelField' and 'optgroupValueField'.

**Comment by khan8698** [comment]
@nanya any solution for the problem relating to defining unique field names. i am getting same problem. in which i can assign data when valueField is "value"  and labelField is "label" rest is not seems to be working and it is still geting objects with values mentioned before even i have changed them in config object

**Comment by nanya** [comment]
@khan8698 No, I haven't found a solution :(

**Comment by khan8698** [comment]
@nanya Please verify that the custom variable names are not double strings eg not in this format '"value"' and should be like this 'value'. this was the blunder from my side may be it works for you

**Comment by NicholasAzar** [comment]
Hi, i added a working option group example [here](https://github.com/NicholasAzar/ng-selectize-demo/tree/master/src/app/home/option-group-example).. let me know if you still have any issues
