### ISSUE TITLE
Angular run change detection on every mouse move event[Performance issue]

### ISSUE THREAD

**Issue by karangarg45** [NicholasAzar/ng-selectize#37]
I started using ng selectize in my application and i started experiencing some serious performance issue.Did a little debugging and found that in selectize standalone.js there is a mouse move event attached to the $window(line 1392)
Could you please look into it as it forces the angular to run change detection on every mouse move which then leads to all model calculations bound to my component?

**Comment by NicholasAzar** [comment]
Hi @karangarg45 -- I'll take a look and let you know. Thanks for bringing this up.

**Comment by NicholasAzar** [comment]
@karangarg45 I added a potential [fix](https://github.com/NicholasAzar/ng-selectize/commit/187bb8c03b9e427229eaa2ccaed64ed432799cdf) to the fix(37) branch for review. It did resolve the problem for me from how I was able to replicate it, and still seems to maintain original functionality.

Let me know if this is a good solution and i'll merge to master and release.

@BenevidesLecontes could you please review this as well and let me know if it seems ok?

**Comment by BenevidesLecontes** [comment]
@NicholasAzar ill try to review soon i can.

**Comment by karangarg45** [comment]
@NicholasAzar  Any update on this?When you are going to merge this with the main branch?
The solution seems to be working fine for me.

**Comment by NicholasAzar** [comment]
@karangarg45 Thanks for verifying, will merge and publish tomorrow.

**Comment by NicholasAzar** [comment]
fix(37) branch merged into master and published in 1.0.10.
