### ISSUE TITLE
Populating ng-selectize box with initial values

### ISSUE THREAD

**Issue by millturnK** [NicholasAzar/ng-selectize#42]
Hi there,
We are totally stuck. We are trying to set our selectize box with the current tags (array of Tag objects) assigned to a requirement. We understand how to set the default options on the form with the "name" values of our objects (in this case "Tag" objects) - i.e. not just strings but objects. We are using reactive forms. When we manually set the value of the control "tagsCtrl", we can see that is being set with these objects but they are not being displayed.
Also when the user creates a new Requirement and selects tags to apply, it just passes them back as strings not Tag objects.
My questions for you are:
- does ng-selectize support objects rather than just strings?
- does it support reactive forms? (we tried setting the default Tags with ngModel but this didn't work).

Here is our HTML:
<ng-selectize [options]="allTags" id="tagsCtrl" formControlName="tagsCtrl" [config]="config" ></ng-selectize>
Here is the relevant section of our component class (the config is per your example):
 private successfulRetrieve(nfrs: NFR[]) {

        // assuming only one matching that ID!!!
        this.nfr = nfrs[0];
        console.log("successful retrieve: ", this.nfr);
        // now populate the fields
        this.category.setValue(this.nfr.category);
        this.subcategory.setValue(this.nfr.subCategory.toLowerCase());
        this.nfrtext.setValue(this.nfr.nfr);
        this.acceptanceTest.setValue(this.nfr.acceptanceTest);
        this.source.setValue(this.nfr.source);
     
         //this.tagsCtrl.setValue(this.nfr.tags);
//nfr.tags is the array of tag objects
        this.tagsCtrl.setValue(this.nfr.tags);
        //this.tagsCtrl.setValue(["TEST"]);

    }

**Comment by NicholasAzar** [comment]
Hi @millturnK -- I'll take a look at this.... haven't tried it in a while but i'm pretty sure that setting the value through a form control should reflect appropriately in the ui.
I'll work off of my form-example in [ng-selectize-demo](https://github.com/NicholasAzar/ng-selectize-demo/tree/master/src/app/home/form-example), but if you have you code up in a repo anywhere, I might be able to provide a more meaningful example.

**Comment by NicholasAzar** [comment]
@millturnK
Code for a working example can be found in the test(42) branch of ng-selectize-demo [here](https://github.com/NicholasAzar/ng-selectize-demo/tree/test(42)/src/app/home/form-example)
Here's a quick summary:
Options are:
```
{       label: 'Angular',
	value: 'angular',
	code: 'NG'
}, {
	label: 'ReactJS',
	value: 'reactjs',
	code: 'RJS'
}, {
	label: 'Ember JS',
	value: 'emberjs',
	code: 'emjs'
}, {
	label: 'Ruby on Rails',
	value: 'ruby_on_rails',
	code: 'ROR'
}
```

Config is:
```
{
	labelField: 'label',
	valueField: 'value',
	maxItems: 2,
	highlight: false,
	create:false,
	persist:true,
	plugins: ['dropdown_direction', 'remove_button'],
	dropdownDirection: 'down'
}
```
Form group is:
```
FORM_GROUP_EXAMPLE = {
	requiredDropdownExample: ['angular', Validators.required],
	firstName: ['', Validators.required],
	lastName: ['', Validators.required]
}
```
being used like this:
`this.formGroupExample = this.formBuilder.group(FORM_GROUP_EXAMPLE);
`
Programatically setting the value of the form to ['angular', 'reactjs'], would be done like:
`this.formGroupExample.controls['requiredDropdownExample'].setValue(['angular', 'reactjs'])
`
And the UI would display 'Angular' and 'ReactJS'.

Hope this helps.
