### ISSUE TITLE
Caret positioning in textfield

### ISSUE THREAD

**Issue by nanya** [NicholasAzar/ng-selectize#44]
Hi,

After selecting an option and click again in the textfield, the caret is positioned far away from the text contained in the textfield. Please can you explain why this happens? Thanks!

**Comment by NicholasAzar** [comment]
Hi @nanya , sorry for the delay in responding.. do you happen to have a screenshot for me to see what you mean? Playing around with what i have working right now and the caret placement seems to be ok..
