### ISSUE TITLE
Search text is not retained after selecting a value from the dropdown

### ISSUE THREAD

**Issue by karangarg45** [NicholasAzar/ng-selectize#48]
suppose i search on a text 'Test' and as soon as i select a result from the dropdown  the search criteria gets cleared.Is it the expected behaviour? Also is it possible to make it configurable?

**Comment by NicholasAzar** [comment]
Hi @karangarg45, the functionality as you described is of the base selectize.js library and not (intentionally) modified by this module. I believe this change will need to be done on their end.

**Comment by karangarg45** [comment]
okay then i guess nothing can be done about this on your side.
I have one more query if user removes any selected option then dropdown is open again.is it also the behaviour from selectize.js library?

**Comment by NicholasAzar** [comment]
@karangarg45 partially, since this module does maintain the binding between the selectize.js values and the angular layer. I suspect you might want to take a look at the 'persist' option in the selectize config.
