### ISSUE TITLE
Model value is not updated in onChange

### ISSUE THREAD

**Issue by shafaqkazmi** [NicholasAzar/ng-selectize#49]
I'm working in angular 4 and i'm facing an issue that if I try to access the model value inside onChange method, it doesn't provides me. However if I check the model value after some interval it worked. 

**HTML**
```
 <ng-selectize [(ngModel)]="selectedSymbol" name="symbol" [config]="symbolSelectizeConfig"
 [options]="symbolDropdownOptions" [placeholder]="'Symbol'"></ng-selectize>
```
**JS**
```
this.myConfig = {
      labelField: 'symbol',
      valueField: 'symbol',
      searchField: ['symbol', 'issuerName'],
      onChange: this.getStatusData.bind(this)
      }
}
getStatusData () {
  console.log(this.selectedSymbol) // this returns null
}
```

**Comment by NicholasAzar** [comment]
Hi @shafaqkazmi, could you try making the following change and seeing if it works out? I'll take a look at cleaning up the interface in the mean time.

```
<ng-selectize [ngModel]="selectedSymbol" (ngModelChange)="getStatusData($event)" name="symbol" [config]="symbolSelectizeConfig" [options]="symbolDropdownOptions" [placeholder]="'Symbol'"></ng-selectize>
```
With the above, you can remove the `onChange `field from `myConfig`.

**Comment by shafaqkazmi** [comment]
@NicholasAzar : this doesn't work too. `this.selectedSymbol` is still not updated in `getStatusData` method.

**Comment by NicholasAzar** [comment]
@shafaqkazmi i didn't read the question close enough the first time...

add output brackets to ngModel as well then, as follows:

`<ng-selectize [(ngModel)]="selectedSymbol" (ngModelChange)="getStatusData($event)" name="symbol" [config]="symbolSelectizeConfig" [options]="symbolDropdownOptions" [placeholder]="'Symbol'"></ng-selectize>`

**Comment by shafaqkazmi** [comment]
This also doesn't work for me :(

**Comment by roweldeguzman** [comment]
@NicholasAzar i think this is because NgModel is not in sync with options value is change.

adding code below will update the value of NgModel and might be the answer that @shafaqkazmi is looking for.
`import { NgModel } from '@angular/forms';`
`providers: [NgModel]`

```
constructor(private ngModel: NgModel) { }
onBlurEvent() {
    if (this.ngModel.valueAccessor != null){
        if (this.selectize.settings.mode == 'single'){
            this.ngModel.update.emit(this.selectize.items[0]);
        } else {
	    this.ngModel.update.emit(this.selectize.items);
        }
    }
		
    if (this.formControl) {
	this.formControl.markAsTouched();
    }
    this.onBlur.emit();
    this.evalHasError();
}
```

**Comment by shafaqkazmi** [comment]
Issue was auto resolved after updating the version
