### ISSUE TITLE
Incorrect peer dependency zone.js

### ISSUE THREAD

**Issue by Akeru** [NicholasAzar/ng-selectize#51]
When trying to install using the follwing NPM command : npm i --save ng-selectize jquery selectize

The is warning is displayed :
npm WARN ng-selectize@1.0.11 requires a peer of zone.js@^0.7.2 but none was installed.

**Comment by lyslim** [comment]
We had the same issue while trying to integrate whitesource in our project, even a simple `npm list` will pop issue like below:
``-- UNMET PEER DEPENDENCY zone.js@0.8.16

npm ERR! peer dep missing: zone.js@^0.7.2, required by ng-selectize@1.0.11`

I checked the `package.json` from latest master branch - it seems the dependency to `zone.js` is already bumped to `^0.8.4` which would suit what we need. @NicholasAzar, would you plan to publish this soon?

**Comment by NicholasAzar** [comment]
Hi, this should be fixed in https://github.com/NicholasAzar/ng-selectize/commit/29faa740168682699df12bc1ca67d153eeb962c3 and published in 1.1.0. Let me know if you still have any issues.
