### ISSUE TITLE
refreshOptions() working?

### ISSUE THREAD

**Issue by DucNHoang** [NicholasAzar/ng-selectize#55]
Hi Nicholas, how could I invoke the refreshOptions() function with using jquery cuz I want my app to retrieve options based on the selected item of a previous field and inject them to the current field. Kinda stuck at this stage.

**Comment by NicholasAzar** [comment]
Hi @DucNHoang ng-selectize should automatically reflect any changes in options you pass in to the component. You shouldn't need to call refreshOptions explicitly.
If you need a function to react to the change in selection, use (ngModelChange).
