### ISSUE TITLE
Cannot populate items when (typeof value == 'number')

### ISSUE THREAD

**Issue by thanhnguyenp** [NicholasAzar/ng-selectize#63]
Dear,

I have met an issue with ng-selectize. When the (typeof value == 'number') the dropdown doesn't populate items and selected item(s). I have to manually convert my model value and list values to string.

I guess the issue is in the same place of code with this PR: https://github.com/NicholasAzar/ng-selectize/pull/61

Please help me to check it.

Thank you

**Comment by Gregcop1** [comment]
I've submitted a PR for this, check #64

**Comment by NicholasAzar** [comment]
Included in 1.1.1
