### ISSUE TITLE
Upgrading Angular dependency

### ISSUE THREAD

**Issue by justinlee0777** [NicholasAzar/ng-selectize#69]
Will this library upgrade its Angular dependency up to Angular 5? My team is trying to move to Angular 5 but we're getting conflicts with ng-selectize when doing so.

**Comment by dilipkosuri** [comment]
Hello @justinlee0777 , Does ng-selectize work with Angular 5?

**Comment by justinlee0777** [comment]
The initial issue wasn't so much that ng-selectize didn't work, but that ng-selectize depended specifically on Angular 4.
This issue had been resolved for a while now. I'll close the thread.
